-- MySQL Script generated by MySQL Workbench
-- Sun Jan 17 14:52:21 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema dvd_store
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dvd_store
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dvd_store` DEFAULT CHARACTER SET utf8mb4 ;
USE `dvd_store` ;

-- -----------------------------------------------------
-- Table `dvd_store`.`city`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dvd_store`.`city` (
  `cityID` INT(11) NOT NULL AUTO_INCREMENT,
  `cityName` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`cityID`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `dvd_store`.`d_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dvd_store`.`d_user` (
  `uID` INT(11) NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(20) NOT NULL,
  `lastName` VARCHAR(20) NOT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `pass` VARCHAR(80) NOT NULL,
  `mobile` CHAR(11) NULL DEFAULT NULL,
  `cityID` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`uID`),
  UNIQUE INDEX `email` (`email` ASC) VISIBLE,
  UNIQUE INDEX `mobile` (`mobile` ASC) VISIBLE,
  INDEX `cityID` (`cityID` ASC) VISIBLE,
  CONSTRAINT `d_user_ibfk_1`
    FOREIGN KEY (`cityID`)
    REFERENCES `dvd_store`.`city` (`cityID`))
ENGINE = InnoDB
AUTO_INCREMENT = 49
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `dvd_store`.`photo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dvd_store`.`photo` (
  `pID` INT(11) NOT NULL AUTO_INCREMENT,
  `pName` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`pID`))
ENGINE = InnoDB
AUTO_INCREMENT = 54
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `dvd_store`.`movie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dvd_store`.`movie` (
  `movieID` INT(11) NOT NULL AUTO_INCREMENT,
  `mName` VARCHAR(80) NULL DEFAULT NULL,
  `mRate` FLOAT(3,1) NULL DEFAULT NULL,
  `pID` INT(11) NULL DEFAULT NULL,
  `uID` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`movieID`),
  UNIQUE INDEX `m_Name_uID` (`mName` ASC, `uID` ASC) VISIBLE,
  INDEX `pID` (`pID` ASC) VISIBLE,
  INDEX `uID` (`uID` ASC) VISIBLE,
  CONSTRAINT `movie_ibfk_1`
    FOREIGN KEY (`pID`)
    REFERENCES `dvd_store`.`photo` (`pID`),
  CONSTRAINT `movie_ibfk_2`
    FOREIGN KEY (`uID`)
    REFERENCES `dvd_store`.`d_user` (`uID`))
ENGINE = InnoDB
AUTO_INCREMENT = 41
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
